import type { CaseStudy, Homepage, Service, TeamMember } from "@/types";

export const fallbackCaseStudies: CaseStudy[] = [
  {
    _id: "luminary",
    title: "Luminary Rebrand",
    slug: { current: "luminary" },
    client: "Luminary Health",
    excerpt: "Complete visual identity for a wellness platform.",
    year: 2025,
    color: "#4A7C6F",
    coverImage: null,
    services: [{ _id: "brand-strategy", title: "Branding" }],
  },
  {
    _id: "prism",
    title: "Prism Dashboard",
    slug: { current: "prism" },
    client: "Prism Analytics",
    excerpt: "Data visualization suite for enterprise analytics.",
    year: 2025,
    color: "#6366F1",
    coverImage: null,
    services: [{ _id: "product-design", title: "Product Design" }],
  },
  {
    _id: "vanta",
    title: "Vanta Launch",
    slug: { current: "vanta" },
    client: "Vanta Security",
    excerpt: "Marketing site and brand launch for a cybersecurity startup.",
    year: 2024,
    color: "#C8956C",
    coverImage: null,
    services: [{ _id: "web-development", title: "Web Development" }],
  },
  {
    _id: "echo",
    title: "Echo Spatial",
    slug: { current: "echo" },
    client: "Echo Audio",
    excerpt: "Immersive audio product experience with spatial sound.",
    year: 2024,
    color: "#DC2626",
    coverImage: null,
    services: [{ _id: "motion-3d", title: "3D / WebGL" }],
  },
  {
    _id: "meridian",
    title: "Meridian OS",
    slug: { current: "meridian" },
    client: "Meridian Labs",
    excerpt: "Operating system design language and component library.",
    year: 2024,
    color: "#0EA5E9",
    coverImage: null,
    services: [{ _id: "product-design-2", title: "Product Design" }],
  },
  {
    _id: "terraform",
    title: "Terraform Identity",
    slug: { current: "terraform" },
    client: "TerraForm Co",
    excerpt: "Sustainable architecture firm identity and web presence.",
    year: 2023,
    color: "#8B5CF6",
    coverImage: null,
    services: [{ _id: "branding-2", title: "Branding" }],
  },
];

export const fallbackServices: Service[] = [
  {
    _id: "brand-strategy",
    title: "Brand Strategy",
    description: "We uncover what makes your brand unique and build a strategic foundation that guides every creative decision.",
    icon: "bar-chart-3",
    features: ["Brand positioning", "Competitive analysis", "Audience research", "Messaging framework", "Brand architecture"],
    order: 1,
  },
  {
    _id: "visual-identity",
    title: "Visual Identity",
    description: "Complete identity systems that are distinctive, scalable, and built to last across every touchpoint.",
    icon: "palette",
    features: ["Logo & mark design", "Typography systems", "Color palettes", "Brand guidelines", "Asset libraries"],
    order: 2,
  },
  {
    _id: "digital-design",
    title: "Digital Design",
    description: "User interfaces and experiences that are intuitive, beautiful, and grounded in real user behavior.",
    icon: "layers",
    features: ["UI/UX design", "Design systems", "Prototyping", "User research", "Accessibility"],
    order: 3,
  },
  {
    _id: "web-development",
    title: "Web Development",
    description: "High-performance applications built with modern frameworks, deployed on edge infrastructure.",
    icon: "code-2",
    features: ["Next.js / React", "Headless CMS", "E-commerce", "API integrations", "Performance optimization"],
    order: 4,
  },
  {
    _id: "motion-3d",
    title: "Motion & 3D",
    description: "Cinematic animations, WebGL experiences, and immersive environments that push the boundaries of the web.",
    icon: "video",
    features: ["Three.js / WebGL", "GSAP animations", "Video production", "Interactive experiences", "Spatial design"],
    order: 5,
  },
  {
    _id: "product-design",
    title: "Product Design",
    description: "End-to-end product thinking from concept to launch, for apps and platforms people love to use.",
    icon: "smartphone",
    features: ["Product strategy", "Interaction design", "Design sprints", "Usability testing", "Launch support"],
    order: 6,
  },
];

export const fallbackTeamMembers: TeamMember[] = [
  {
    _id: "alex-rivera",
    name: "Alex Rivera",
    role: "Founder & Creative Director",
    bio: "Leads strategy and creative direction across brand, digital, and motion engagements.",
    order: 1,
  },
  {
    _id: "maya-chen",
    name: "Maya Chen",
    role: "Head of Design",
    bio: "Shapes interface systems and editorial visual language with a focus on polish and clarity.",
    order: 2,
  },
  {
    _id: "james-okafor",
    name: "James Okafor",
    role: "Lead Developer",
    bio: "Builds performant digital experiences that balance ambition with maintainability.",
    order: 3,
  },
  {
    _id: "sofia-laurent",
    name: "Sofia Laurent",
    role: "Strategy Director",
    bio: "Connects research, positioning, and messaging into a coherent product narrative.",
    order: 4,
  },
  {
    _id: "kai-tanaka",
    name: "Kai Tanaka",
    role: "Motion Designer",
    bio: "Crafts restrained motion systems and cinematic transitions that support the story.",
    order: 5,
  },
  {
    _id: "zara-patel",
    name: "Zara Patel",
    role: "Project Manager",
    bio: "Keeps multidisciplinary projects focused, predictable, and high-quality from kickoff to launch.",
    order: 6,
  },
];

export const fallbackHomepage: Homepage = {
  heroHeadline: "We craft digital experiences that move people",
  heroSubline: "Strategy, design, and technology for brands that refuse to blend in.",
  featuredWork: fallbackCaseStudies.slice(0, 5),
  testimonials: [
    {
      quote: "Muse helped us turn a complex product story into a brand people immediately understood and remembered.",
      author: "Sarah Chen",
      role: "CEO",
      company: "Luminary Health",
    },
    {
      quote: "The work felt premium from day one, but what impressed us most was how clearly every decision tied back to strategy.",
      author: "Marcus Webb",
      role: "CTO",
      company: "Prism Analytics",
    },
  ],
};
